
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = {
  code: string;
  name: string;
  flag: string;
};

export const languages: Language[] = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
  { code: 'pt', name: 'Português', flag: '🇵🇹' },
  { code: 'sv', name: 'Svenska', flag: '🇸🇪' },
];

type LanguageContextType = {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem('preferredLanguage');
    return savedLanguage || 'en';
  });

  useEffect(() => {
    localStorage.setItem('preferredLanguage', language);
  }, [language]);

  // Simple translation function
  const t = (key: string): string => {
    if (!translations[language]) return translations.en[key] || key;
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Translations object containing all text in different languages
const translations: Record<string, Record<string, string>> = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.facilities': 'Facilities',
    'nav.rooms': 'Rooms',
    'nav.foodAndDrink': 'Food & Drink',
    'nav.contactUs': 'Contact Us',
    'nav.dashboard': 'Dashboard',
    'nav.myProfile': 'My Profile',
    'nav.myBookings': 'My Bookings',
    'nav.signOut': 'Sign Out',
    'nav.signIn': 'Sign In',
    
    // Rooms page
    'rooms.title': 'Available Rooms',
    'rooms.checkIn': 'Check-in Date',
    'rooms.checkOut': 'Check-out Date',
    'rooms.guests': 'Guests',
    'rooms.pickDate': 'Pick a date',
    'rooms.searchAvailability': 'Search Availability',
    'rooms.searching': 'Searching for',
    'rooms.night': 'night',
    'rooms.nights': 'nights',
    'rooms.guest': 'guest',
    'rooms.guestsPlural': 'guests',
    'rooms.pricePerNight': '/night',
    'rooms.capacity': 'Capacity:',
    'rooms.bookNow': 'Book Now',
    'rooms.noRooms': 'No rooms available',
    'rooms.tryDifferentDates': 'Please try different dates or check back later.',
    'rooms.refreshResults': 'Refresh Results',
    'rooms.errorLoading': 'Error Loading Rooms',
    'rooms.errorDescription': 'We encountered an error while loading the available rooms.',
    'rooms.tryAgain': 'Try Again',
    'rooms.authRequired': 'Authentication required',
    'rooms.loginRequired': 'Please log in to book a room',
    'rooms.invalidDates': 'Invalid dates',
    'rooms.selectDates': 'Please select check-in and check-out dates',
    
    // Room amenities
    'amenities.wifi': 'WiFi',
    'amenities.breakfast': 'Breakfast',
    
    // Facilities page
    'facilities.title': 'Our Facilities',
    'facilities.subtitle': 'Discover our premium facilities designed to enhance your stay and provide unforgettable experiences.',
    'facilities.allFacilities': 'All Facilities',
    'facilities.dining': 'Dining',
    'facilities.wellness': 'Wellness',
    'facilities.services': 'Services',
    'facilities.loading': 'Loading facilities...',
    'facilities.error': 'Error loading facilities. Please try again later.',
    'facilities.learnMore': 'Learn More',
    
    // Contact page
    'contact.title': 'Contact Us',
    'contact.subtitle': "We'd love to hear from you. Reach out to us with any questions or requests.",
    'contact.getInTouch': 'Get in Touch',
    'contact.getInTouchText': 'Have questions about your reservation, our facilities, or anything else? We\'re here to help you make the most of your stay with us.',
    'contact.address': 'Address',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.hours': 'Hours',
    'contact.sendMessage': 'Send Us a Message',
    'contact.name': 'Name',
    'contact.yourName': 'Your name',
    'contact.yourEmail': 'Your email',
    'contact.subject': 'Subject',
    'contact.selectSubject': 'Select a subject',
    'contact.reservation': 'Reservation Inquiry',
    'contact.services': 'Services Information',
    'contact.feedback': 'Feedback',
    'contact.complaint': 'Complaint',
    'contact.other': 'Other',
    'contact.message': 'Message',
    'contact.yourMessage': 'Your message',
    'contact.sending': 'Sending...',
    'contact.send': 'Send Message',
    'contact.messageSent': 'Message Sent!',
    'contact.responseMessage': "We'll get back to you as soon as possible.",
    
    // Food and Drink page
    'foodDrink.title': 'Food & Drink Menu',
    'foodDrink.subtitle': 'Explore our delicious food and refreshing drinks',
    'foodDrink.allItems': 'All Items',
    'foodDrink.food': 'Food',
    'foodDrink.drinks': 'Drinks',
    'foodDrink.addToCart': 'Add to Cart',
    'foodDrink.categories.all': 'All',
    'foodDrink.categories.main': 'Main Course',
    'foodDrink.categories.starter': 'Starters',
    'foodDrink.categories.dessert': 'Desserts',
    'foodDrink.categories.cocktail': 'Cocktails',
    'foodDrink.categories.wine': 'Wine',
    'foodDrink.categories.beer': 'Beer',
    'foodDrink.categories.coffee': 'Coffee',
    'foodDrink.categories.tea': 'Tea',
    'foodDrink.categories.soft': 'Soft Drinks',
    'foodDrink.searchMenu': 'Search menu...'
  },
  fr: {
    // Navbar
    'nav.home': 'Accueil',
    'nav.facilities': 'Installations',
    'nav.rooms': 'Chambres',
    'nav.foodAndDrink': 'Restauration',
    'nav.contactUs': 'Contactez-nous',
    'nav.dashboard': 'Tableau de bord',
    'nav.myProfile': 'Mon profil',
    'nav.myBookings': 'Mes réservations',
    'nav.signOut': 'Déconnexion',
    'nav.signIn': 'Connexion',
    
    // Rooms page
    'rooms.title': 'Chambres disponibles',
    'rooms.checkIn': 'Date d\'arrivée',
    'rooms.checkOut': 'Date de départ',
    'rooms.guests': 'Clients',
    'rooms.pickDate': 'Choisir une date',
    'rooms.searchAvailability': 'Rechercher disponibilité',
    'rooms.searching': 'Recherche pour',
    'rooms.night': 'nuit',
    'rooms.nights': 'nuits',
    'rooms.guest': 'personne',
    'rooms.guestsPlural': 'personnes',
    'rooms.pricePerNight': '/nuit',
    'rooms.capacity': 'Capacité:',
    'rooms.bookNow': 'Réserver',
    'rooms.noRooms': 'Aucune chambre disponible',
    'rooms.tryDifferentDates': 'Veuillez essayer des dates différentes ou vérifier plus tard.',
    'rooms.refreshResults': 'Actualiser les résultats',
    'rooms.errorLoading': 'Erreur de chargement',
    'rooms.errorDescription': 'Nous avons rencontré une erreur lors du chargement des chambres disponibles.',
    'rooms.tryAgain': 'Réessayez',
    'rooms.authRequired': 'Authentification requise',
    'rooms.loginRequired': 'Veuillez vous connecter pour réserver une chambre',
    'rooms.invalidDates': 'Dates invalides',
    'rooms.selectDates': 'Veuillez sélectionner les dates d\'arrivée et de départ',
    
    // Room amenities
    'amenities.wifi': 'WiFi',
    'amenities.breakfast': 'Petit-déjeuner',
    
    // Facilities page
    'facilities.title': 'Nos Installations',
    'facilities.subtitle': 'Découvrez nos installations haut de gamme conçues pour améliorer votre séjour et offrir des expériences inoubliables.',
    'facilities.allFacilities': 'Toutes les installations',
    'facilities.dining': 'Restauration',
    'facilities.wellness': 'Bien-être',
    'facilities.services': 'Services',
    'facilities.loading': 'Chargement des installations...',
    'facilities.error': 'Erreur lors du chargement des installations. Veuillez réessayer plus tard.',
    'facilities.learnMore': 'En savoir plus',
    
    // Contact page
    'contact.title': 'Contactez-nous',
    'contact.subtitle': "Nous aimerions avoir de vos nouvelles. Contactez-nous pour toute question ou demande.",
    'contact.getInTouch': 'Prenez contact',
    'contact.getInTouchText': 'Vous avez des questions sur votre réservation, nos installations ou autre chose? Nous sommes là pour vous aider à profiter au maximum de votre séjour.',
    'contact.address': 'Adresse',
    'contact.phone': 'Téléphone',
    'contact.email': 'Email',
    'contact.hours': 'Horaires',
    'contact.sendMessage': 'Envoyez-nous un message',
    'contact.name': 'Nom',
    'contact.yourName': 'Votre nom',
    'contact.yourEmail': 'Votre email',
    'contact.subject': 'Sujet',
    'contact.selectSubject': 'Sélectionnez un sujet',
    'contact.reservation': 'Demande de réservation',
    'contact.services': 'Informations sur les services',
    'contact.feedback': 'Commentaires',
    'contact.complaint': 'Réclamation',
    'contact.other': 'Autre',
    'contact.message': 'Message',
    'contact.yourMessage': 'Votre message',
    'contact.sending': 'Envoi en cours...',
    'contact.send': 'Envoyer le message',
    'contact.messageSent': 'Message envoyé!',
    'contact.responseMessage': "Nous vous répondrons dès que possible.",
    
    // Food and Drink page
    'foodDrink.title': 'Menu Nourriture & Boissons',
    'foodDrink.subtitle': 'Explorez notre délicieuse nourriture et nos boissons rafraîchissantes',
    'foodDrink.allItems': 'Tous les articles',
    'foodDrink.food': 'Nourriture',
    'foodDrink.drinks': 'Boissons',
    'foodDrink.addToCart': 'Ajouter au panier',
    'foodDrink.categories.all': 'Tout',
    'foodDrink.categories.main': 'Plats principaux',
    'foodDrink.categories.starter': 'Entrées',
    'foodDrink.categories.dessert': 'Desserts',
    'foodDrink.categories.cocktail': 'Cocktails',
    'foodDrink.categories.wine': 'Vin',
    'foodDrink.categories.beer': 'Bière',
    'foodDrink.categories.coffee': 'Café',
    'foodDrink.categories.tea': 'Thé',
    'foodDrink.categories.soft': 'Boissons sans alcool',
    'foodDrink.searchMenu': 'Rechercher dans le menu...'
  },
  es: {
    // Navbar
    'nav.home': 'Inicio',
    'nav.facilities': 'Instalaciones',
    'nav.rooms': 'Habitaciones',
    'nav.foodAndDrink': 'Comida y bebida',
    'nav.contactUs': 'Contáctenos',
    'nav.dashboard': 'Panel de control',
    'nav.myProfile': 'Mi perfil',
    'nav.myBookings': 'Mis reservas',
    'nav.signOut': 'Cerrar sesión',
    'nav.signIn': 'Iniciar sesión',
    
    // Rooms page
    'rooms.title': 'Habitaciones disponibles',
    'rooms.checkIn': 'Fecha de llegada',
    'rooms.checkOut': 'Fecha de salida',
    'rooms.guests': 'Huéspedes',
    'rooms.pickDate': 'Elegir fecha',
    'rooms.searchAvailability': 'Buscar disponibilidad',
    'rooms.searching': 'Buscando por',
    'rooms.night': 'noche',
    'rooms.nights': 'noches',
    'rooms.guest': 'huésped',
    'rooms.guestsPlural': 'huéspedes',
    'rooms.pricePerNight': '/noche',
    'rooms.capacity': 'Capacidad:',
    'rooms.bookNow': 'Reservar ahora',
    'rooms.noRooms': 'No hay habitaciones disponibles',
    'rooms.tryDifferentDates': 'Intente con otras fechas o vuelva más tarde.',
    'rooms.refreshResults': 'Actualizar resultados',
    'rooms.errorLoading': 'Error al cargar habitaciones',
    'rooms.errorDescription': 'Encontramos un error al cargar las habitaciones disponibles.',
    'rooms.tryAgain': 'Intentar de nuevo',
    'rooms.authRequired': 'Autenticación requerida',
    'rooms.loginRequired': 'Inicie sesión para reservar una habitación',
    'rooms.invalidDates': 'Fechas inválidas',
    'rooms.selectDates': 'Por favor seleccione fechas de llegada y salida',
    
    // Room amenities
    'amenities.wifi': 'WiFi',
    'amenities.breakfast': 'Desayuno',
    
    // Facilities page
    'facilities.title': 'Nuestras Instalaciones',
    'facilities.subtitle': 'Descubra nuestras instalaciones premium diseñadas para mejorar su estancia y proporcionar experiencias inolvidables.',
    'facilities.allFacilities': 'Todas las instalaciones',
    'facilities.dining': 'Restauración',
    'facilities.wellness': 'Bienestar',
    'facilities.services': 'Servicios',
    'facilities.loading': 'Cargando instalaciones...',
    'facilities.error': 'Error al cargar las instalaciones. Por favor intente más tarde.',
    'facilities.learnMore': 'Más información',
    
    // Contact page
    'contact.title': 'Contáctenos',
    'contact.subtitle': "Nos encantaría saber de usted. Comuníquese con nosotros para cualquier pregunta o solicitud.",
    'contact.getInTouch': 'Póngase en contacto',
    'contact.getInTouchText': '¿Tiene preguntas sobre su reserva, nuestras instalaciones o cualquier otra cosa? Estamos aquí para ayudarle a aprovechar al máximo su estancia.',
    'contact.address': 'Dirección',
    'contact.phone': 'Teléfono',
    'contact.email': 'Correo electrónico',
    'contact.hours': 'Horarios',
    'contact.sendMessage': 'Envíenos un mensaje',
    'contact.name': 'Nombre',
    'contact.yourName': 'Su nombre',
    'contact.yourEmail': 'Su correo electrónico',
    'contact.subject': 'Asunto',
    'contact.selectSubject': 'Seleccione un asunto',
    'contact.reservation': 'Consulta de reserva',
    'contact.services': 'Información de servicios',
    'contact.feedback': 'Comentarios',
    'contact.complaint': 'Queja',
    'contact.other': 'Otro',
    'contact.message': 'Mensaje',
    'contact.yourMessage': 'Su mensaje',
    'contact.sending': 'Enviando...',
    'contact.send': 'Enviar mensaje',
    'contact.messageSent': '¡Mensaje enviado!',
    'contact.responseMessage': "Nos pondremos en contacto con usted lo antes posible.",
    
    // Food and Drink page
    'foodDrink.title': 'Menú de Comida y Bebida',
    'foodDrink.subtitle': 'Explore nuestra deliciosa comida y refrescantes bebidas',
    'foodDrink.allItems': 'Todos los artículos',
    'foodDrink.food': 'Comida',
    'foodDrink.drinks': 'Bebidas',
    'foodDrink.addToCart': 'Añadir al carrito',
    'foodDrink.categories.all': 'Todos',
    'foodDrink.categories.main': 'Platos principales',
    'foodDrink.categories.starter': 'Entrantes',
    'foodDrink.categories.dessert': 'Postres',
    'foodDrink.categories.cocktail': 'Cócteles',
    'foodDrink.categories.wine': 'Vino',
    'foodDrink.categories.beer': 'Cerveza',
    'foodDrink.categories.coffee': 'Café',
    'foodDrink.categories.tea': 'Té',
    'foodDrink.categories.soft': 'Refrescos',
    'foodDrink.searchMenu': 'Buscar en el menú...'
  },
  de: {
    // Navbar
    'nav.home': 'Startseite',
    'nav.facilities': 'Einrichtungen',
    'nav.rooms': 'Zimmer',
    'nav.foodAndDrink': 'Essen & Trinken',
    'nav.contactUs': 'Kontakt',
    'nav.dashboard': 'Übersicht',
    'nav.myProfile': 'Mein Profil',
    'nav.myBookings': 'Meine Buchungen',
    'nav.signOut': 'Abmelden',
    'nav.signIn': 'Anmelden',
    
    // Rooms page
    'rooms.title': 'Verfügbare Zimmer',
    'rooms.checkIn': 'Anreisedatum',
    'rooms.checkOut': 'Abreisedatum',
    'rooms.guests': 'Gäste',
    'rooms.pickDate': 'Datum wählen',
    'rooms.searchAvailability': 'Verfügbarkeit suchen',
    'rooms.searching': 'Suche nach',
    'rooms.night': 'Nacht',
    'rooms.nights': 'Nächte',
    'rooms.guest': 'Gast',
    'rooms.guestsPlural': 'Gäste',
    'rooms.pricePerNight': '/Nacht',
    'rooms.capacity': 'Kapazität:',
    'rooms.bookNow': 'Jetzt buchen',
    'rooms.noRooms': 'Keine Zimmer verfügbar',
    'rooms.tryDifferentDates': 'Bitte versuchen Sie andere Daten oder schauen Sie später wieder vorbei.',
    'rooms.refreshResults': 'Ergebnisse aktualisieren',
    'rooms.errorLoading': 'Fehler beim Laden der Zimmer',
    'rooms.errorDescription': 'Beim Laden der verfügbaren Zimmer ist ein Fehler aufgetreten.',
    'rooms.tryAgain': 'Erneut versuchen',
    'rooms.authRequired': 'Authentifizierung erforderlich',
    'rooms.loginRequired': 'Bitte melden Sie sich an, um ein Zimmer zu buchen',
    'rooms.invalidDates': 'Ungültige Daten',
    'rooms.selectDates': 'Bitte An- und Abreisedatum auswählen',
    
    // Room amenities
    'amenities.wifi': 'WLAN',
    'amenities.breakfast': 'Frühstück',
    
    // Facilities page
    'facilities.title': 'Unsere Einrichtungen',
    'facilities.subtitle': 'Entdecken Sie unsere erstklassigen Einrichtungen, die Ihren Aufenthalt verbessern und unvergessliche Erlebnisse bieten.',
    'facilities.allFacilities': 'Alle Einrichtungen',
    'facilities.dining': 'Gastronomie',
    'facilities.wellness': 'Wellness',
    'facilities.services': 'Dienstleistungen',
    'facilities.loading': 'Einrichtungen werden geladen...',
    'facilities.error': 'Fehler beim Laden der Einrichtungen. Bitte versuchen Sie es später erneut.',
    'facilities.learnMore': 'Mehr erfahren',
    
    // Contact page
    'contact.title': 'Kontakt',
    'contact.subtitle': "Wir würden uns freuen, von Ihnen zu hören. Kontaktieren Sie uns bei Fragen oder Wünschen.",
    'contact.getInTouch': 'Nehmen Sie Kontakt auf',
    'contact.getInTouchText': 'Haben Sie Fragen zu Ihrer Reservierung, unseren Einrichtungen oder etwas anderem? Wir sind hier, um Ihnen zu helfen, Ihren Aufenthalt bestmöglich zu gestalten.',
    'contact.address': 'Adresse',
    'contact.phone': 'Telefon',
    'contact.email': 'E-Mail',
    'contact.hours': 'Öffnungszeiten',
    'contact.sendMessage': 'Senden Sie uns eine Nachricht',
    'contact.name': 'Name',
    'contact.yourName': 'Ihr Name',
    'contact.yourEmail': 'Ihre E-Mail',
    'contact.subject': 'Betreff',
    'contact.selectSubject': 'Betreff auswählen',
    'contact.reservation': 'Reservierungsanfrage',
    'contact.services': 'Informationen zu Dienstleistungen',
    'contact.feedback': 'Feedback',
    'contact.complaint': 'Beschwerde',
    'contact.other': 'Anderes',
    'contact.message': 'Nachricht',
    'contact.yourMessage': 'Ihre Nachricht',
    'contact.sending': 'Wird gesendet...',
    'contact.send': 'Nachricht senden',
    'contact.messageSent': 'Nachricht gesendet!',
    'contact.responseMessage': "Wir melden uns so schnell wie möglich bei Ihnen.",
    
    // Food and Drink page
    'foodDrink.title': 'Speisen & Getränke Menü',
    'foodDrink.subtitle': 'Entdecken Sie unsere köstlichen Speisen und erfrischenden Getränke',
    'foodDrink.allItems': 'Alle Artikel',
    'foodDrink.food': 'Speisen',
    'foodDrink.drinks': 'Getränke',
    'foodDrink.addToCart': 'In den Warenkorb',
    'foodDrink.categories.all': 'Alle',
    'foodDrink.categories.main': 'Hauptgerichte',
    'foodDrink.categories.starter': 'Vorspeisen',
    'foodDrink.categories.dessert': 'Desserts',
    'foodDrink.categories.cocktail': 'Cocktails',
    'foodDrink.categories.wine': 'Wein',
    'foodDrink.categories.beer': 'Bier',
    'foodDrink.categories.coffee': 'Kaffee',
    'foodDrink.categories.tea': 'Tee',
    'foodDrink.categories.soft': 'Erfrischungsgetränke',
    'foodDrink.searchMenu': 'Menü durchsuchen...'
  },
  ar: {
    // Navbar - Note: Arabic is right-to-left
    'nav.home': 'الرئيسية',
    'nav.facilities': 'المرافق',
    'nav.rooms': 'الغرف',
    'nav.foodAndDrink': 'الطعام والشراب',
    'nav.contactUs': 'اتصل بنا',
    'nav.dashboard': 'لوحة التحكم',
    'nav.myProfile': 'ملفي الشخصي',
    'nav.myBookings': 'حجوزاتي',
    'nav.signOut': 'تسجيل الخروج',
    'nav.signIn': 'تسجيل الدخول',
    
    // Rooms page
    'rooms.title': 'الغرف المتاحة',
    'rooms.checkIn': 'تاريخ الوصول',
    'rooms.checkOut': 'تاريخ المغادرة',
    'rooms.guests': 'الضيوف',
    'rooms.pickDate': 'اختر تاريخ',
    'rooms.searchAvailability': 'بحث عن توفر',
    'rooms.searching': 'البحث عن',
    'rooms.night': 'ليلة',
    'rooms.nights': 'ليالي',
    'rooms.guest': 'ضيف',
    'rooms.guestsPlural': 'ضيوف',
    'rooms.pricePerNight': '/ليلة',
    'rooms.capacity': 'السعة:',
    'rooms.bookNow': 'احجز الآن',
    'rooms.noRooms': 'لا توجد غرف متاحة',
    'rooms.tryDifferentDates': 'الرجاء تجربة تواريخ مختلفة أو التحقق لاحقا.',
    'rooms.refreshResults': 'تحديث النتائج',
    'rooms.errorLoading': 'خطأ في تحميل الغرف',
    'rooms.errorDescription': 'واجهنا خطأ أثناء تحميل الغرف المتاحة.',
    'rooms.tryAgain': 'حاول مرة أخرى',
    'rooms.authRequired': 'المصادقة مطلوبة',
    'rooms.loginRequired': 'يرجى تسجيل الدخول لحجز غرفة',
    'rooms.invalidDates': 'تواريخ غير صالحة',
    'rooms.selectDates': 'يرجى تحديد تواريخ الوصول والمغادرة',
    
    // Room amenities
    'amenities.wifi': 'واي فاي',
    'amenities.breakfast': 'إفطار',
    
    // Facilities page
    'facilities.title': 'مرافقنا',
    'facilities.subtitle': 'اكتشف مرافقنا المتميزة المصممة لتعزيز إقامتك وتوفير تجارب لا تُنسى.',
    'facilities.allFacilities': 'جميع المرافق',
    'facilities.dining': 'المطاعم',
    'facilities.wellness': 'الصحة واللياقة',
    'facilities.services': 'الخدمات',
    'facilities.loading': 'جاري تحميل المرافق...',
    'facilities.error': 'خطأ في تحميل المرافق. يرجى المحاولة مرة أخرى لاحقًا.',
    'facilities.learnMore': 'اعرف المزيد',
    
    // Contact page
    'contact.title': 'اتصل بنا',
    'contact.subtitle': "نود أن نسمع منك. تواصل معنا بشأن أي أسئلة أو طلبات.",
    'contact.getInTouch': 'تواصل معنا',
    'contact.getInTouchText': 'هل لديك أسئلة حول حجزك، مرافقنا، أو أي شيء آخر؟ نحن هنا لمساعدتك في الاستفادة القصوى من إقامتك معنا.',
    'contact.address': 'العنوان',
    'contact.phone': 'الهاتف',
    'contact.email': 'البريد الإلكتروني',
    'contact.hours': 'ساعات العمل',
    'contact.sendMessage': 'أرسل لنا رسالة',
    'contact.name': 'الاسم',
    'contact.yourName': 'اسمك',
    'contact.yourEmail': 'بريدك الإلكتروني',
    'contact.subject': 'الموضوع',
    'contact.selectSubject': 'اختر موضوعًا',
    'contact.reservation': 'استفسار عن الحجز',
    'contact.services': 'معلومات عن الخدمات',
    'contact.feedback': 'تعليق',
    'contact.complaint': 'شكوى',
    'contact.other': 'آخر',
    'contact.message': 'الرسالة',
    'contact.yourMessage': 'رسالتك',
    'contact.sending': 'جارٍ الإرسال...',
    'contact.send': 'إرسال الرسالة',
    'contact.messageSent': 'تم إرسال الرسالة!',
    'contact.responseMessage': "سنعاود الاتصال بك في أقرب وقت ممكن.",
    
    // Food and Drink page
    'foodDrink.title': 'قائمة الطعام والشراب',
    'foodDrink.subtitle': 'استكشف طعامنا اللذيذ ومشروباتنا المنعشة',
    'foodDrink.allItems': 'جميع العناصر',
    'foodDrink.food': 'الطعام',
    'foodDrink.drinks': 'المشروبات',
    'foodDrink.addToCart': 'أضف إلى السلة',
    'foodDrink.categories.all': 'الكل',
    'foodDrink.categories.main': 'الأطباق الرئيسية',
    'foodDrink.categories.starter': 'المقبلات',
    'foodDrink.categories.dessert': 'الحلويات',
    'foodDrink.categories.cocktail': 'الكوكتيلات',
    'foodDrink.categories.wine': 'النبيذ',
    'foodDrink.categories.beer': 'البيرة',
    'foodDrink.categories.coffee': 'القهوة',
    'foodDrink.categories.tea': 'الشاي',
    'foodDrink.categories.soft': 'المشروبات الغازية',
    'foodDrink.searchMenu': 'البحث في القائمة...'
  },
  pt: {
    // Navbar
    'nav.home': 'Início',
    'nav.facilities': 'Instalações',
    'nav.rooms': 'Quartos',
    'nav.foodAndDrink': 'Comida e Bebida',
    'nav.contactUs': 'Contato',
    'nav.dashboard': 'Painel de Controle',
    'nav.myProfile': 'Meu Perfil',
    'nav.myBookings': 'Minhas Reservas',
    'nav.signOut': 'Sair',
    'nav.signIn': 'Entrar',
    
    // Rooms page
    'rooms.title': 'Quartos Disponíveis',
    'rooms.checkIn': 'Data de Check-in',
    'rooms.checkOut': 'Data de Check-out',
    'rooms.guests': 'Hóspedes',
    'rooms.pickDate': 'Escolha uma data',
    'rooms.searchAvailability': 'Buscar Disponibilidade',
    'rooms.searching': 'Buscando por',
    'rooms.night': 'noite',
    'rooms.nights': 'noites',
    'rooms.guest': 'hóspede',
    'rooms.guestsPlural': 'hóspedes',
    'rooms.pricePerNight': '/noite',
    'rooms.capacity': 'Capacidade:',
    'rooms.bookNow': 'Reservar Agora',
    'rooms.noRooms': 'Não há quartos disponíveis',
    'rooms.tryDifferentDates': 'Por favor, tente datas diferentes ou volte mais tarde.',
    'rooms.refreshResults': 'Atualizar Resultados',
    'rooms.errorLoading': 'Erro ao Carregar Quartos',
    'rooms.errorDescription': 'Encontramos um erro ao carregar os quartos disponíveis.',
    'rooms.tryAgain': 'Tentar Novamente',
    'rooms.authRequired': 'Autenticação necessária',
    'rooms.loginRequired': 'Por favor, faça login para reservar um quarto',
    'rooms.invalidDates': 'Datas inválidas',
    'rooms.selectDates': 'Por favor, selecione as datas de check-in e check-out',
    
    // Room amenities
    'amenities.wifi': 'WiFi',
    'amenities.breakfast': 'Café da manhã',
    
    // Facilities page
    'facilities.title': 'Nossas Instalações',
    'facilities.subtitle': 'Descubra nossas instalações premium projetadas para melhorar sua estadia e proporcionar experiências inesquecíveis.',
    'facilities.allFacilities': 'Todas as Instalações',
    'facilities.dining': 'Gastronomia',
    'facilities.wellness': 'Bem-estar',
    'facilities.services': 'Serviços',
    'facilities.loading': 'Carregando instalações...',
    'facilities.error': 'Erro ao carregar instalações. Por favor, tente novamente mais tarde.',
    'facilities.learnMore': 'Saiba Mais',
    
    // Contact page
    'contact.title': 'Contato',
    'contact.subtitle': "Adoraríamos ouvir de você. Entre em contato conosco com qualquer pergunta ou solicitação.",
    'contact.getInTouch': 'Entre em contato',
    'contact.getInTouchText': 'Tem dúvidas sobre sua reserva, nossas instalações ou qualquer outra coisa? Estamos aqui para ajudá-lo a aproveitar ao máximo sua estadia conosco.',
    'contact.address': 'Endereço',
    'contact.phone': 'Telefone',
    'contact.email': 'E-mail',
    'contact.hours': 'Horários',
    'contact.sendMessage': 'Envie-nos uma mensagem',
    'contact.name': 'Nome',
    'contact.yourName': 'Seu nome',
    'contact.yourEmail': 'Seu e-mail',
    'contact.subject': 'Assunto',
    'contact.selectSubject': 'Selecione um assunto',
    'contact.reservation': 'Consulta de Reserva',
    'contact.services': 'Informações de Serviços',
    'contact.feedback': 'Feedback',
    'contact.complaint': 'Reclamação',
    'contact.other': 'Outro',
    'contact.message': 'Mensagem',
    'contact.yourMessage': 'Sua mensagem',
    'contact.sending': 'Enviando...',
    'contact.send': 'Enviar Mensagem',
    'contact.messageSent': 'Mensagem Enviada!',
    'contact.responseMessage': "Entraremos em contato o mais breve possível.",
    
    // Food and Drink page
    'foodDrink.title': 'Menu de Comida e Bebida',
    'foodDrink.subtitle': 'Explore nossa deliciosa comida e bebidas refrescantes',
    'foodDrink.allItems': 'Todos os Itens',
    'foodDrink.food': 'Comida',
    'foodDrink.drinks': 'Bebidas',
    'foodDrink.addToCart': 'Adicionar ao Carrinho',
    'foodDrink.categories.all': 'Todos',
    'foodDrink.categories.main': 'Pratos Principais',
    'foodDrink.categories.starter': 'Entradas',
    'foodDrink.categories.dessert': 'Sobremesas',
    'foodDrink.categories.cocktail': 'Coquetéis',
    'foodDrink.categories.wine': 'Vinho',
    'foodDrink.categories.beer': 'Cerveja',
    'foodDrink.categories.coffee': 'Café',
    'foodDrink.categories.tea': 'Chá',
    'foodDrink.categories.soft': 'Refrigerantes',
    'foodDrink.searchMenu': 'Pesquisar no menu...'
  },
  sv: {
    // Navbar
    'nav.home': 'Hem',
    'nav.facilities': 'Faciliteter',
    'nav.rooms': 'Rum',
    'nav.foodAndDrink': 'Mat & Dryck',
    'nav.contactUs': 'Kontakta Oss',
    'nav.dashboard': 'Instrumentpanel',
    'nav.myProfile': 'Min Profil',
    'nav.myBookings': 'Mina Bokningar',
    'nav.signOut': 'Logga Ut',
    'nav.signIn': 'Logga In',
    
    // Rooms page
    'rooms.title': 'Tillgängliga Rum',
    'rooms.checkIn': 'Incheckning',
    'rooms.checkOut': 'Utcheckning',
    'rooms.guests': 'Gäster',
    'rooms.pickDate': 'Välj datum',
    'rooms.searchAvailability': 'Sök Tillgänglighet',
    'rooms.searching': 'Söker efter',
    'rooms.night': 'natt',
    'rooms.nights': 'nätter',
    'rooms.guest': 'gäst',
    'rooms.guestsPlural': 'gäster',
    'rooms.pricePerNight': '/natt',
    'rooms.capacity': 'Kapacitet:',
    'rooms.bookNow': 'Boka Nu',
    'rooms.noRooms': 'Inga rum tillgängliga',
    'rooms.tryDifferentDates': 'Prova andra datum eller återkom senare.',
    'rooms.refreshResults': 'Uppdatera Resultat',
    'rooms.errorLoading': 'Fel vid Laddning av Rum',
    'rooms.errorDescription': 'Vi stötte på ett fel när tillgängliga rum laddades.',
    'rooms.tryAgain': 'Försök Igen',
    'rooms.authRequired': 'Autentisering krävs',
    'rooms.loginRequired': 'Vänligen logga in för att boka ett rum',
    'rooms.invalidDates': 'Ogiltiga datum',
    'rooms.selectDates': 'Välj in- och utcheckningsdatum',
    
    // Room amenities
    'amenities.wifi': 'WiFi',
    'amenities.breakfast': 'Frukost',
    
    // Facilities page
    'facilities.title': 'Våra Faciliteter',
    'facilities.subtitle': 'Upptäck våra förstklassiga faciliteter designade för att förbättra din vistelse och ge oförglömliga upplevelser.',
    'facilities.allFacilities': 'Alla Faciliteter',
    'facilities.dining': 'Matservering',
    'facilities.wellness': 'Välbefinnande',
    'facilities.services': 'Tjänster',
    'facilities.loading': 'Laddar faciliteter...',
    'facilities.error': 'Fel vid laddning av faciliteter. Försök igen senare.',
    'facilities.learnMore': 'Läs Mer',
    
    // Contact page
    'contact.title': 'Kontakta Oss',
    'contact.subtitle': "Vi skulle gärna höra från dig. Kontakta oss med eventuella frågor eller önskemål.",
    'contact.getInTouch': 'Kom i kontakt',
    'contact.getInTouchText': 'Har du frågor om din bokning, våra faciliteter eller något annat? Vi finns här för att hjälpa dig att få ut det mesta av din vistelse hos oss.',
    'contact.address': 'Adress',
    'contact.phone': 'Telefon',
    'contact.email': 'E-post',
    'contact.hours': 'Öppettider',
    'contact.sendMessage': 'Skicka oss ett meddelande',
    'contact.name': 'Namn',
    'contact.yourName': 'Ditt namn',
    'contact.yourEmail': 'Din e-post',
    'contact.subject': 'Ämne',
    'contact.selectSubject': 'Välj ett ämne',
    'contact.reservation': 'Bokningsförfrågan',
    'contact.services': 'Tjänstinformation',
    'contact.feedback': 'Feedback',
    'contact.complaint': 'Klagomål',
    'contact.other': 'Annat',
    'contact.message': 'Meddelande',
    'contact.yourMessage': 'Ditt meddelande',
    'contact.sending': 'Skickar...',
    'contact.send': 'Skicka Meddelande',
    'contact.messageSent': 'Meddelande skickat!',
    'contact.responseMessage': "Vi återkommer till dig så snart som möjligt.",
    
    // Food and Drink page
    'foodDrink.title': 'Mat & Dryck Meny',
    'foodDrink.subtitle': 'Utforska vår utsökta mat och uppfriskande drycker',
    'foodDrink.allItems': 'Alla artiklar',
    'foodDrink.food': 'Mat',
    'foodDrink.drinks': 'Drycker',
    'foodDrink.addToCart': 'Lägg i kundvagn',
    'foodDrink.categories.all': 'Alla',
    'foodDrink.categories.main': 'Huvudrätter',
    'foodDrink.categories.starter': 'Förrätter',
    'foodDrink.categories.dessert': 'Efterrätter',
    'foodDrink.categories.cocktail': 'Cocktails',
    'foodDrink.categories.wine': 'Vin',
    'foodDrink.categories.beer': 'Öl',
    'foodDrink.categories.coffee': 'Kaffe',
    'foodDrink.categories.tea': 'Te',
    'foodDrink.categories.soft': 'Läskedrycker',
    'foodDrink.searchMenu': 'Sök i menyn...'
  }
};

export default LanguageContext;
